// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSXJL8AQdK3sDdO61FYY88ZkDL0vDlJIk',
    appId: '1:1022035705774:web:f2cfc2a11b1a3dcbbd923f',
    messagingSenderId: '1022035705774',
    projectId: 'teacheraccount-cec5e',
    authDomain: 'teacheraccount-cec5e.firebaseapp.com',
    storageBucket: 'teacheraccount-cec5e.appspot.com',
    measurementId: 'G-MSDM7R2F7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2YUUQWpRjydBWWtBpGxGtU1JRUd69-HQ',
    appId: '1:1022035705774:android:8abd1bf7d4d9ff4ebd923f',
    messagingSenderId: '1022035705774',
    projectId: 'teacheraccount-cec5e',
    storageBucket: 'teacheraccount-cec5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrEnFz_U1cZD_fC7tnM0MFB-bX04uHIuw',
    appId: '1:1022035705774:ios:8280e4aa4be753bfbd923f',
    messagingSenderId: '1022035705774',
    projectId: 'teacheraccount-cec5e',
    storageBucket: 'teacheraccount-cec5e.appspot.com',
    iosBundleId: 'com.example.teacherAppAccount',
  );
}
